version: '3'
services:
  blynk_database:
    env_file: .env
    container_name: blynk_database
    image: bitnami/postgresql
    restart: 'always'
    volumes:
      - './init-tables-db.sh:/docker-entrypoint-initdb.d/init-tables-db.sh'
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USER}'
      - 'BLYNK_SERVER_VERSION=${BLYNK_SERVER_VERSION}'
    networks:
      - blynk_network
  blynk_server:
    env_file: .env
    container_name: blynk-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BLYNK_SERVER_VERSION: ${BLYNK_SERVER_VERSION}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
    environment:
      ENABLE_DB: "true"
      ENABLE_RAW_DB_DATA_STORE: "true"
    ports:
      - ${HARDWARE_MQTT_PORT}:${HARDWARE_MQTT_PORT}
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${HTTPS_PORT}:${HTTPS_PORT}
    volumes:
      - blynk_volume:/data
    networks:
      - blynk_network
    restart: 'always'
    depends_on:
      - blynk_database
    links:
      - blynk_database
networks:
  blynk_network:
    external: true
volumes:
  blynk_volume:
    external: true